### ISSUE TITLE
生成PDF 时顺序错乱的问题

### ISSUE THREAD

**Issue by Yohoa** [liuqi0725/image2PDF#1]
Liu Qi,

您好！

非常感谢您创建「image2PDF」项目，我已将您开源的的程序码使用在了我的图书馆数字馆藏图书下载项目中。这是引用了您的程序码的项目地址：https://github.com/Yohoa/Download-Scanned-Book-from-the-Library-of-NUAA 

但使用时，我遇到了生成PDF 页码错乱的问题。

尽管我已经将一个文件夹的图片按照次序（00001.jpg, 00002.jpg....) 命名，但在产生PDF 档的时候，页码仍然出现了无序的现象；最终生成的PDF 的页码排序方式似乎没有规律。

这个情况在Mac 和iOS的Pythonista 中同样出现。

希望您已了解我在使用您的程序码时候所遇到的情况。

谢谢您！

Raphael Yang

**Comment by liuqi0725** [comment]
您好针对你之前提出的文件名排序，我对版本代码进行了一部分简化和拆分。并针对文件名排序已经做了专门的修改，包括对复杂的文件排序规则。    array.sort() 只能解决比较标准的文件名格式。  复杂的不行。 

感谢你在您的项目中，使用我开源的内容。
